[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "psuf"
version = "0.1.0"
description = "Praktikum strojnega učenja v fiziki"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
include = ["psuf*"]

[tool.mypy]
disable_error_code = ["import-untyped"]
